Numerical Python
* Faster Arrays than List
* Inbuilt Mathematical Operations on arrays

In [3]:
import numpy as np

In [4]:
from time import process_time

In [5]:
l1 = [i for i in range(1000000)]

start = process_time()

l1 = [i+5 for i in l1]

end = process_time()

print(end-start)

0.25


In [6]:
numpyArray = np.array([i for i in range(1000000)])
start = process_time()

numpyArray += 5 #It will auto do the addition of every element

end = process_time()

print(end-start)

0.0


In [7]:
l1 = [1,2,3,4,5]
print(l1)
type(l1)

[1, 2, 3, 4, 5]


list

In [8]:
npa = np.array([1,2,3,4,5])
print(npa)
type(npa)

[1 2 3 4 5]


numpy.ndarray

ndarray is N Dimensional Array

In [12]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [16]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
b.shape

(2, 5)

In [20]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)], dtype=float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [28]:
d = np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
e = np.ones((3,3,3),dtype = int)
print(e)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [32]:
f = np.full((2,5),7)
print(f)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [36]:
g = np.eye(4, dtype=int) #Identity Matrix
print(g)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [46]:
h = np.random.random((6,3))
print(h)

[[0.27322296 0.29354267 0.22512792]
 [0.85289462 0.25906686 0.73419383]
 [0.01382904 0.02368226 0.44052517]
 [0.29695921 0.5683573  0.95115154]
 [0.06176036 0.2962232  0.86492344]
 [0.36512528 0.81852069 0.28569022]]


In [50]:
i = np.random.randint(1,100,(3,3))
print(i)

[[30 34 57]
 [29 56  3]
 [36 98 49]]


In [58]:
j = np.linspace(10,30,6) # evenly space 6 values from 10 to 30 
print(j)

[10. 14. 18. 22. 26. 30.]


In [62]:
k = np.arange(10,30,2) # evenly space values on the step of 2
print(k)

[10 12 14 16 18 20 22 24 26 28]


In [90]:
l = [1,2,3,4,5]
l = np.asarray(l)
print(l)
type(l)

[1 2 3 4 5]


numpy.ndarray

In [80]:
print(i)
print("shape =",i.shape)
print("dimension =", i.ndim)
print("no. of elements =",i.size)

[[30 34 57]
 [29 56  3]
 [36 98 49]]
shape = (3, 3)
dimension = 2
no. of elements = 9


In [92]:
m=[1,2,3]
n=[4,5,6]
print(m+n)

[1, 2, 3, 4, 5, 6]


In [112]:
o = np.random.randint(1,5,(3,3))
p = np.random.randint(6,10,(3,3))

print("o \n",o)
print("p \n",p)
print("o+p \n",o+p)
print("o-p \n",o-p)
print("o*p \n",o*p)
print("p//o \n",p//o)
print("o%p \n",o%p)

o 
 [[2 4 1]
 [1 3 1]
 [1 1 2]]
p 
 [[8 9 8]
 [9 7 9]
 [7 6 6]]
o+p 
 [[10 13  9]
 [10 10 10]
 [ 8  7  8]]
o-p 
 [[-6 -5 -7]
 [-8 -4 -8]
 [-6 -5 -4]]
o*p 
 [[16 36  8]
 [ 9 21  9]
 [ 7  6 12]]
p//o 
 [[4 2 8]
 [9 2 9]
 [7 6 3]]
o%p 
 [[2 4 1]
 [1 3 1]
 [1 1 2]]


In [116]:
q = np.random.randint(1,10,(3,2))
print(q)
q = np.transpose(q)
print(q)

[[8 9]
 [6 8]
 [1 9]]
[[8 6 1]
 [9 8 9]]


In [126]:
r = np.random.randint(1,10,(2,3))
print(r)
print(r.shape)
print('\n')
s = r.reshape((3,2))
print(s)
print(s.shape)

[[7 7 4]
 [2 5 1]]
(2, 3)


[[7 7]
 [4 2]
 [5 1]]
(3, 2)
